// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiptServer.Data;

#nullable disable

namespace RecieptServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203200244_updatingDtos")]
    partial class updatingDtos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReceiptServer.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Milk",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bread",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eggs",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Notebook",
                            Price = 5.00m
                        });
                });

            modelBuilder.Entity("ReceiptServer.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 0m
                        });
                });

            modelBuilder.Entity("ReceiptServer.Models.ReceiptArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            Quantity = 2,
                            ReceiptId = 1,
                            Total = 0m,
                            UnitPrice = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            Quantity = 1,
                            ReceiptId = 1,
                            Total = 0m,
                            UnitPrice = 2.49m
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            Quantity = 1,
                            ReceiptId = 2,
                            Total = 0m,
                            UnitPrice = 3.50m
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 4,
                            Quantity = 3,
                            ReceiptId = 2,
                            Total = 0m,
                            UnitPrice = 5.00m
                        });
                });

            modelBuilder.Entity("ReceiptServer.Models.ReceiptArticle", b =>
                {
                    b.HasOne("ReceiptServer.Models.Article", "Article")
                        .WithMany("ReceiptArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReceiptServer.Models.Receipt", "Receipt")
                        .WithMany("ReceiptArticles")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ReceiptServer.Models.Article", b =>
                {
                    b.Navigation("ReceiptArticles");
                });

            modelBuilder.Entity("ReceiptServer.Models.Receipt", b =>
                {
                    b.Navigation("ReceiptArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
