// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiptServer.Data;

#nullable disable

namespace RecieptServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203233920_updatedExemples")]
    partial class updatedExemples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReceiptServer.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Name = "Milk",
                            Price = 22.99m
                        },
                        new
                        {
                            Id = 1002,
                            Name = "Bread",
                            Price = 38.49m
                        },
                        new
                        {
                            Id = 1003,
                            Name = "Eggs",
                            Price = 37.50m
                        },
                        new
                        {
                            Id = 1004,
                            Name = "Notebook",
                            Price = 85.00m
                        });
                });

            modelBuilder.Entity("ReceiptServer.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1001L);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("Receipts");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Date = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 6.47m
                        },
                        new
                        {
                            Id = 1002,
                            Date = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 18.50m
                        });
                });

            modelBuilder.Entity("ReceiptServer.Models.ReceiptArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptArticles");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            ArticleId = 1001,
                            Quantity = 2,
                            ReceiptId = 1001,
                            Total = 45.98m,
                            UnitPrice = 22.99m
                        },
                        new
                        {
                            Id = 1002,
                            ArticleId = 1002,
                            Quantity = 1,
                            ReceiptId = 1001,
                            Total = 38.49m,
                            UnitPrice = 38.49m
                        },
                        new
                        {
                            Id = 1003,
                            ArticleId = 1003,
                            Quantity = 1,
                            ReceiptId = 1002,
                            Total = 37.50m,
                            UnitPrice = 37.50m
                        },
                        new
                        {
                            Id = 1004,
                            ArticleId = 1004,
                            Quantity = 3,
                            ReceiptId = 1002,
                            Total = 255.00m,
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 1005,
                            ArticleId = 1001,
                            Quantity = 1,
                            ReceiptId = 1003,
                            Total = 22.99m,
                            UnitPrice = 22.99m
                        },
                        new
                        {
                            Id = 1006,
                            ArticleId = 1002,
                            Quantity = 2,
                            ReceiptId = 1004,
                            Total = 76.98m,
                            UnitPrice = 38.49m
                        },
                        new
                        {
                            Id = 1007,
                            ArticleId = 1003,
                            Quantity = 4,
                            ReceiptId = 1005,
                            Total = 150.00m,
                            UnitPrice = 37.50m
                        },
                        new
                        {
                            Id = 1008,
                            ArticleId = 1004,
                            Quantity = 1,
                            ReceiptId = 1006,
                            Total = 85.00m,
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 1009,
                            ArticleId = 1002,
                            Quantity = 1,
                            ReceiptId = 1007,
                            Total = 38.49m,
                            UnitPrice = 38.49m
                        },
                        new
                        {
                            Id = 1010,
                            ArticleId = 1001,
                            Quantity = 3,
                            ReceiptId = 1008,
                            Total = 68.97m,
                            UnitPrice = 22.99m
                        },
                        new
                        {
                            Id = 1011,
                            ArticleId = 1004,
                            Quantity = 2,
                            ReceiptId = 1009,
                            Total = 170.00m,
                            UnitPrice = 85.00m
                        });
                });

            modelBuilder.Entity("ReceiptServer.Models.ReceiptArticle", b =>
                {
                    b.HasOne("ReceiptServer.Models.Article", "Article")
                        .WithMany("ReceiptArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReceiptServer.Models.Receipt", "Receipt")
                        .WithMany("ReceiptArticles")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ReceiptServer.Models.Article", b =>
                {
                    b.Navigation("ReceiptArticles");
                });

            modelBuilder.Entity("ReceiptServer.Models.Receipt", b =>
                {
                    b.Navigation("ReceiptArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
